README.md

- close #209
- README에서 사용하던 메인 배너 이미지 경로가 유효하지 않아서 이미지가 그려지지 않는 문제 수정

README 이미지 경로 수정

---

feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt

- close #182 
- 후원사 이미지를 클릭하면 `Sponsor` 모델에 정의된 URL에 브라우저로 연결된다.

[Sponsor] 후원사 이미지 클릭 시 브라우저로 홈페이지 연결

---

feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt

- close #139
- 발표 개요 내용이 존재하면 해당 텍스트를 보여줍니다.
- 원활한 코드리뷰를 위해 SessionDetailScreen 파일에 속하는 Composable 들에 대해  @Preview 를 추가하였습니다.
Before | After

[Session] 세션 상세 - 발표 개요

---

feature/home/src/main/java/com/droidknights/app2023/feature/home/HomeScreen.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
feature/setting/src/main/java/com/droidknights/app2023/feature/setting/SettingScreen.kt

- close #162
- close #165 
=> 레이아웃 깨짐의 원인이 scrollState 의 부재였던 것 같습니다
- 각 탭에 vertcalScroll 에 scrollState 값 추가
Before | After
:--: | :--:

[Bug] 각 탭에서 스크롤이 되지않습니다

---

feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt

- close #161 
- 기존 후원사 카드 내부 로고 배치 수정
- 자동/무한 스크롤 기능 제거
- 이 기능은 더 이상 유효하지 않으므로 제거합니다.

[Home] 후원사 카드 내부 로고 배치 수정 

---

feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionChip.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt

- close #232
- 화면에 사용되는 글씨 색을 onSecondaryContainer로 통일하였습니다.
- 세션 상세 정보 화면에 Speaker 정보를 추가하였습니다.
- 공통으로 사용하던 SessionChips를 제거하였습니다
-> 추후 PR에서 세션 목록화면의 SessionCard에 북마크 칩이 들어가는것을 고려하여,
분기를 태우거나 Composable 함수를 열어두는것보다 제거하는것이 더 낫다고 판단하였는데
잘못 판단했다 생각되신다면 의견 주시면 감사하겠습니다!
- 스펙상 스피커가 여러명인것 같은데 실제로는 한 명만 존재하고 디자인에 고려되어있지 않아서
여러명인 경우의 디자인을 고려하지 않고 작성하였습니다!
- none
Before | After
:--: | :--:

[Session] 세션 상세정보 화면 디자인 변경

---

feature/setting/src/main/java/com/droidknights/app2023/feature/setting/SettingScreen.kt

설정 화면에서 modifier 적용 순서 차이로 카드의 elevation에 의한 shadow가 짤리고 있었는데, modifier의 순서를 바꿔 해결했습니다.
none
Before | After
:--: | :--:

[Bug] 설정 화면에서 카드의 그림자가 가려지는 문제 해결

---

feature/bookmark/build.gradle.kts
feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkScreen.kt

- close #246 
- 관련 이슈 #222 
- 불필요하게 리컴포지션 될 수 있는 List 함수 패러미터를 ImmutableList로 변경한다

[feature/#246] bookmarkItems의 타입을 ImmutableList로 변경

---

core/designsystem/src/main/java/com/droidknights/app2023/core/designsystem/component/TopAppBar.kt
feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
feature/main/src/main/java/com/droidknights/app2023/feature/main/MainScreen.kt

컴포넌트를 연타할 때 발생하는 중복 호출 이슈를 수정하였습니다.
- TopAppBar의 뒤로가기(종료) 버튼을 연타하면 Home 화면을 넘어가 뒤로가는 경우가 발생합니다.
- currentDestination이 Home이 아닌 경우에만 뒤로가도록 수정하였습니다.
- 홈 화면에서 session 이동 카드를 TopAppBar 영역에 위치한 후 연타하면 화면이 계속 넘어갑니다.
- navigate 시 이동할 destination과 currentDestination이 같지 않은 경우에만 이동하도록 함수를 구현하려하였으나
- contributor 화면에서 AppBar 영역을 터치하여도 투과되어 뒤에 있는 카드가 클릭 되기에
- TopAppBar에 빈 clickable을 제공하여 클릭 이벤트가 투과하는 것을 방지하였습니다.
Before | After
:--: | :--:
Before | After
:--: | :--:

[Bug] 버튼 연타 시 중복 호출 이슈 수정

---

core/data/src/main/java/com/droidknights/app2023/core/data/mapper/SessionMapper.kt
core/data/src/test/java/com/droidknights/app2023/core/data/repository/DefaultSessionRepositoryTest.kt
core/domain/src/test/java/com/droidknights/app2023/core/domain/usecase/GetBookmarkedSessionsUseCaseTest.kt
core/model/src/main/java/com/droidknights/app2023/core/model/Session.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionViewModel.kt
feature/session/src/main/res/drawable/ic_flagbookmark.xml
feature/session/src/test/java/com/droidknights/app2023/feature/session/SessionDetailViewModelTest.kt
feature/session/src/test/java/com/droidknights/app2023/feature/session/SessionViewModelTest.kt

- close #236 
- BookmarkUscase를 활용하여 Bookmarked 된 Id를 매칭하였습니다.
- Session DTO에 isBookmarked라는 Boolean 변수를 추가하여 UIState에서 활용가능하도록 수정하였습니다.
PersistentList 를 사용하는 이유에 대해 인천 IO 세미나를 통해 너무 잘 이해했습니다, 감사합니다 🙇‍♂️
Before | After
:--: | :--:

[Feature/session_bookmark]: 북마크 UI 추가 작업

---

core/data/src/main/java/com/droidknights/app/core/data/repository/DefaultSessionRepository.kt
core/data/src/main/java/com/droidknights/app/core/data/repository/SessionRepository.kt
core/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetBookmarkedSessionIdsUseCase.kt
core/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetBookmarkedSessionsUseCase.kt
core/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetSessionsUseCase.kt
core/domain/src/test/java/com/droidknights/app/core/domain/usecase/FakeSessionRepository.kt
feature/session/src/test/java/com/droidknights/app/feature/session/SessionViewModelTest.kt

- SessionRepository 내에 getBookmarkedSessionIds() 함수는 반환 타입이 Flow<Set<String>> 입니다. 따라서 해당 함수는 suspend 키워드가 필요 없기에 제거하였습니다. 
- 해당 함수를 사용하는 파일(GetBookmarkedSessionIdsUseCase, DefaultSessionRepository, FakeSessionRepository, SessionViewModelTest)에도 변경을 반영하였습니다.

fix: flow 반환 타입 함수 suspend 키워드 제거

---

feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/BookmarkScreen.kt

- 배경에 적용되어 있는 마진을 제거했습니다.
- [디자인](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=869-5053&mode=design&t=rJoYYIzEQY5JJPr9-4)
Before | After
:--: | :--:

[북마크] 배경 margin 제거

---

build-logic/src/main/kotlin/com/droidknights/app/KotlinMultiplatform.kt
build-logic/src/main/kotlin/com/droidknights/app/KotlinMultiplatformIos.kt
build-logic/src/main/kotlin/com/droidknights/app/KotlinMutliplatformAndroid.kt
build-logic/src/main/kotlin/droidknights.kmp.android.gradle.kts
build-logic/src/main/kotlin/droidknights.kmp.ios.gradle.kts

- #273 
- Kotlin Multiplatform 전환 이전에 필요한 Kotlin Multiplatform Gradle Plugin을 미리 제작했습니다.
- Class 형식의 Plugin으로 제작은 많이 해봤는데 함수로 이렇게 제작하는 건 또 새로운 경험이네요.

[feature/register-kmp-plugin] Make Kotlin Multiplatform Android/iOS Plugin

---

core/navigation/build.gradle.kts
core/navigation/src/main/java/com/droidknights/app/core/navigation/RouteModel.kt
feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/navigation/BookmarkNavigation.kt
feature/contributor/src/main/java/com/droidknights/app/feature/contributor/navigation/ContributorNavigation.kt
feature/home/src/main/java/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
feature/main/src/main/java/com/droidknights/app/feature/main/MainNavigator.kt
feature/main/src/main/java/com/droidknights/app/feature/main/MainTab.kt
feature/session/src/main/java/com/droidknights/app/feature/session/navigation/SessionNavigation.kt
feature/setting/src/main/java/com/droidknights/app/feature/setting/navigation/SettingNavigation.kt
gradle/libs.versions.toml

- close #300 
- androidx.navigation 2.8.0-alpha08 버전부터 사용할 수 있는 [Type Safe Navigation](https://medium.com/androiddevelopers/navigation-compose-meet-type-safety-e081fb3cf2f8)을 적용합니다.
https://github.com/droidknights/DroidKnightsApp/assets/54518925/81c2a4cd-b987-49f0-90a1-546cb5bc4d8d

[feature/#300] Apply Type Safe Navigation

---

feature/session/src/main/java/com/droidknights/app/feature/session/SessionDetailScreen.kt
widget/src/main/kotlin/com/droidknights/app/widget/DroidKnightsWidget.kt
widget/src/main/kotlin/com/droidknights/app/widget/WidgetSessionCard.kt
widget/src/main/kotlin/com/droidknights/app/widget/WidgetSessionCardUiState.kt

- #283 
- 복수 발표자일 경우에 세션 상세 정보와, 위젯에 모든 분들이 표시되도록 했습니다.
- 복수 발표자에 관한 디자인 가이드라인이 없었기 때문에 일단 임의로 다른 뷰들을 참고해 Spacer의 크기를 지정했습니다.
- 위젯의 경우, LaunchedEffect 내에서 UiState를 가공하도록 했습니다.
- [세션 상세 정보](https://www.figma.com/design/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?node-id=869-4709&t=brW4ek7b5V4tqVIx-0)
Before | After
:--: | :--:
<video src="https://github.com/droidknights/DroidKnightsApp/assets/81838716/4fb3cb13-b8cb-4f69-9188-0c7e0b6ba8ce" /> | <video src="https://github.com/droidknights/DroidKnightsApp/assets/81838716/5f573065-aac9-42a4-8e24-9f16090ba1e0"/>
Before | After
:--: | :--:

[세션] 복수의 발표자 대응

---

feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/component/EditModeLeadingItem.kt
feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorCard.kt
feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorTopAppBar.kt
feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorTopBanner.kt
feature/session/src/main/java/com/droidknights/app/feature/session/component/SessionChip.kt
feature/session/src/main/java/com/droidknights/app/feature/session/component/SessionTopAppBar.kt

- close #308 
PR 쪼개기 마지막입니다..!
- [이전 PR](https://github.com/droidknights/DroidKnightsApp/pull/327)에서 분리한 컴포넌트에 대한 Preview를 작성하였습니다.
ContributorCard Preview | ContributorTopBanner Preview
:--: | :--:

[개선] 분리한 컴포넌트 preview 작성

---

gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

[#330] 디펜던시 최신화

---

feature/home/src/main/java/com/droidknights/app/feature/home/component/SponsorCard.kt

[#334] 후원사 로고 배경화면 다크테마 대응

---

.github/workflows/android-pull-request-ci.yml
.github/workflows/publish_release.yml
baselineProfile/build.gradle.kts
build-logic/src/main/kotlin/com/droidknights/app/KotlinAndroid.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

(간단히 모든 의존성 버전을 올리고 앱 빌드 + 테스트를 돌려봤는데 잘 돌아가네요. 각 라이브러리들 업데이트 사항은 아직 확인하지 않았습니다.)
---
- close #337 
- compileSdk 34 -> 35
- gradle 8.8 -> 8.10.2
- 그 외 모든 라이브러리의 최신 버전 적용
- Github uploadActifacts action v3 -> v4 
- 2025-01-31부터 업데이트 강제
- ref. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

[라이브러리] 디펜던시 최신화 for 2025 Droid Knights

---

.github/workflows/wasm-build.yml
.github/workflows/web-deploy.yml
composeApp/build.gradle.kts

- close #ISSUE_NUMBER
- wasm 타겟으로 빌드한 결과물을 Github Pages를 통해 배포한다.
- 참고링크: https://github.com/JetBrains/kotlinconf-app/blob/main/.github/workflows/web-deploy.yml

[web-deployment] wasm build 결과물을 github pages에 배포한다

---

.github/workflows/jvm-desktop-build.yml
.github/workflows/jvm-desktop-comment.yml

- Desktop(JVM) 앱 build script 기능을 추가합니다.
- 데스크톱 앱 빌드(현재)
- develop-2025에 PR을 올리고 계속 푸시를 할 때마다 해당 PR에 빌드된 아티팩트 링크를 댓글에 작성
- 아티팩트 유지기간 1일
- develop-2025에 머지될 때 빌드를 해주고 아티팩트를 업로드
- 아티팩트 유지기간 3일
아티팩트 유지기간은 추가 논의 필요합니다.

[jvm-cd] 데스크탑 앱 PR/디벨롭 머지시에 빌드 결과 저장/PR 댓글 다는 기능 추가

---

composeApp/src/androidMain/kotlin/com/droidknights/app/MainActivity.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Scaffold.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Color.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Typography.kt
feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt

- Material 
- 컬러 스킴 임시 구현 (향후 스펙 변화에 따라 변경 가능)
- MainScreen에 Scaffold 추가
- MaterialTheme.colors.background에 따라 앱 배경 및 content color 변경
- Typography 추가
- 2024 디자인 시스템 차용
- 안드로이드
- 다크모드 변경에 따른 시스템 아이콘 컬러 변경 대응
- 데스크탑에서 다크 모드 변경에 앱이 반응하지 않는 [Known Issue](https://youtrack.jetbrains.com/issue/CMP-1986/isSystemInDarkTheme-should-dynamically-update-when-system-theme-is-changed)가 있음
- 플랫폼 특성에 따른 것으로, 이를 이미 해결한 [라이브러리](https://github.com/kdroidFilter/Platform-Tools?tab=readme-ov-file#-dark-mode-detection-module)도 존재
Before | After
:--: | :--:

[init-theme] 테마 초기화

---

.github/workflows/android-build.yml
.github/workflows/ios-arm-build.yml
.github/workflows/ios-intel-build.yml
.github/workflows/jvm-desktop-build.yml
.github/workflows/wasm-build.yml
.github/workflows/web-deploy.yml

- 빌드 트리거의 branch 이름을 `2025/compose-multiplatform`으로 변경

[rename-cmp-branch] 브랜치 이름 변경에 따른 Github Action 설정 파일 대응

---

app-config/app-config-api/build.gradle.kts
app-config/app-config-api/src/main/AndroidManifest.xml
app-config/app-config-api/src/main/java/com/droidknights/app/config/api/DroidknightsBuildConfig.kt
app-config/app-config/build.gradle.kts
app-config/app-config/src/main/AndroidManifest.xml
app-config/app-config/src/main/java/com/droidknights/app/config/DroidknightsBuildConfigImpl.kt
app/build.gradle.kts
build-logic/convention/src/main/kotlin/com/droidknights/app/KotlinAndroid.kt
core/network/network/build.gradle.kts
core/network/network/src/main/java/com/droidknights/app/core/network/di/NetworkModule.kt
settings.gradle.kts

- close #371
- BuildConfig를 모두 false 처리
- 특정 모듈에서만 BuildConfig 활용할 수 있도록 옵션 추가
- App내 BuildConfig 관리용 모듈 추가
- App BuildConfig를 활용하여 api 모듈만 바라보도록 적용

(FEAT)[#371] 내부용 BuildConfig 별도 모듈 추가

---

.github/workflows/android-pull-request-ci.yml
core/data/data-session/src/test/java/com/droidknights/app/core/data/session/fake/FakeSessionPreferencesDataSource.kt
core/data/data-settings/src/test/java/com/droidknights/app/core/data/settings/SettingsRepositoryImplTest.kt
core/network/network/src/test/java/com/droidknights/app/core/network/MockDroidknightsService.kt
feature/contributor/src/androidTest/java/com/droidknights/app/feature/contributor/ContributorScreenTest.kt
feature/home/src/test/java/com/droidknights/app/feature/home/HomeViewModelTest.kt

- close #393
- 모듈을 쪼개면서 변경된 점들이 테스트 코드에 반영되지 않아 테스트가 실패하고 있었음. 코드 현행화를 통해 정상 동작하도록 수정
- (임시) 2025/app을 타겟으로 하는 pr에도 pr ci가 돌도록 수정

(BUG)[#393] 2025 앱 CI 테스트 실패 문제를 해결

---

composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
composeApp/src/wasmJsMain/kotlin/com/droidknights/app/main.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Typography.kt

- close #367 
- 한글 폰트를 사용하여 한글 깨짐 문제 해결
- wasm에서 font를 초기에 불러오지 못하는 문제가 있어서 preloadFont를 사용함
- https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-resources-usage.html#preload-resources-using-the-compose-multiplatform-preload-api
Before | After
:--: | :--:

[wasm-korean] 한글 폰트 사용 + preload로 웹에서 한글 꺠짐 문제 해결

---

core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/ShaderBackground.kt
feature/home/build.gradle.kts
feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSessionCard.kt

- Non-Android 타겟에서 Shader가 정상적으로 노출되지 않는 케이스 수정 
- fix #366
기존 코드는 runtimeEffect에 대해서 early build를 수행하고 있었기에, shader에 필요한 해상도(`uResolution`)에 올바른 값을 전달하지 못하고 있었습니다.
이로 인해, Non-Android 타겟에서 Shader의 시작위치를 제대로 반영하지 못하고 있어서 랜더링 이슈가 발생한 것으로 확인했습니다.
이번 PR에서 Draw 영역의 실제 사이즈를 측정한 이후,
정확한 값을 shader의 uniform에 전달하고 runtimeEffect를 build하도록 수정하였습니다.
아래와 같이, 정확한 사이즈를 update한 뒤 build를 수행하면 문제가 해결됩니다.
```kotlin
.drawWithCache {
val runtimeEffect = buildEffect(shader)
onDrawBehind {
runtimeEffect.update(shader, size.width, size.height)
drawRect(brush = runtimeEffect.build())
}
},
```
확인 부탁드리겠습니다.

[#366] Fix shader issue on Non-Android target

---

core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/di/ApiModule.kt
core/data/data-session/src/main/java/com/droidknights/app/core/data/session/di/ApiModule.kt
core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/di/ApiModule.kt
core/network/network-api/src/main/java/com/droidknights/app/core/network/api/DroidknightsNetwork.kt
core/network/network/src/test/java/com/droidknights/app/core/network/DroidknightsNetworkImplTest.kt

- #438
|-|-|
|----|----|
|before|droidknightsNetwork.create(<br>&nbsp;&nbsp;&nbsp;&nbsp;baseUrl = droidknightsBuildConfig.userDroidknightsUrl(),    <br>&nbsp;&nbsp;&nbsp;&nbsp;service = DroidnightsContributorsApi::class.java<br>)|
|after|droidknightsNetwork.create\<DroidnightsContributorsApi\>(<br>&nbsp;&nbsp;&nbsp;&nbsp;baseUrl = droidknightsBuildConfig.userDroidknightsUrl()<br>)|

(ENG)[droidknights#438] Network 객체 생성시 명시적 클래스 선언을 inline-reified 로 변경

---

gradle/libs.versions.toml

- close #447
- AndroidX 정식 버전 업데이트
- ui-test-junit4의 버전은 BOM에서 관리하는 것으로 보여서 제거 대응했습니다
- https://developer.android.com/develop/ui/compose/bom/bom-mapping?hl=en
- https://developer.android.com/jetpack/androidx/versions/all-channel?hl=en#may_20_2025
Before | After
:--: | :--:

Updates AndroidX May 20, 2025

---

core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/LayeredRadialGradientBackground.kt
feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeMapCard.kt

- close #460 
행사 배치도 카드 배경을 Shader로 작성해보았습니다. 랜더링 되는 원의 크기는 레이아웃의 width 길이에 비례하여 반응적으로 조정되도록 처리했습니다.
추가적으로, 카드 컴포넌트 색상관련해서 기존엔 colorScheme으로 처리되고 있었는데요, 요건 차후 다크모드일 때도 일관적인 색상 유지를 위해 고정 색상으로 할당해두었습니다.
확인 부탁드립니다.
sksl코드에서 색상을 리턴할 때, Non-Android 타겟에서 일반적인 방법으로 투명도가 안먹는 케이스가 존재했습니다.
요 때는 각각 RGB색상에 투명도를 곱해주어야 한다는 사실을 알았습니다.
```c
return half4(1.0, 1.0, 1.0, opacity);
```
```c
return half4(1.0 * opacity, 1.0 * opacity, 1.0 * opacity, opacity);
```

[#460] 행사 배치도 카드 배경 Shader 구현 (Layered Radial Gradient 쉐이더 코드 작성)

---

assets/contributors.json

- 컨트리뷰트 연도가 잘못 표기되어 수정하였습니다.
- cmp 브렌치 core:network 작업이 끝난 뒤 진행할 #439 이슈 해결 전에 미리 오타를 수정하고자 합니다.
- https://raw.githubusercontent.com/haeti-dev/DroidKnightsApp/refs/heads/fix/contributors-year-mismatch/assets/contributors.json 해당 링크 진입 시 수정된 json 에셋을 볼 수 있습니다.

컨트리뷰터 오타 수정 및 닉네임 최신화
